version: "3.8"

services:
  database:
    image: postgres
    container_name: "database"
    ports:
      - 5432:5432
    volumes:
      - pg:/data/postgres
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    networks:
      - c

#  pg_dump:
#    image: postgres
#    command:
#     [
#      "sh",
#     "-c",
#     "PGPASSWORD=test pg_dump -h database -U test -d test > /docker-entrypoint-initdb.d/backup.sql",
#      ]
#    depends_on:
#      - database
#    volumes:
#      - ./backup:/docker-entrypoint-initdb.d
#    networks:
#      - c

volumes:
  pg:
    driver: local

networks:
  c:
    driver: bridge
