version: "3.8"

services:
  database:
    image: postgres
    container_name: "database"
    ports:
      - 5432:5432
    volumes:
      - pg:/data/postgres
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test

volumes:
  pg:
    driver: local
